### ISSUE TITLE
Keybind documentation

### ISSUE THREAD

**Issue by jacobrreed** [mistricky/codesnap.nvim#84]
Can you add your setup for keymaps?

```
    {
      "<leader>ss",
      function()
        vim.cmd("CodeSnap")
      end,
      desc = "CodeSnap",
      mode = "v",
    },

```

Currently this doesnt work, I have to manually visually select, then type the command CodeSnap removing the range selectors `<` and `>`

If i use the above it will just say "no code selected"

**Comment by ak22112** [comment]
@jacobrreed 
This is the best I've managed so far:

```lua
keys = {
    { "<leader>ci", ":CodeSnap<cr>", desc = "CodeSnap", mode = "x" },
},
```

It works fine but due to using the `:` you do briefly see that you've entered command mode. If that doesn't bother you then this will suffice.

I'm yet to find a way to do it silently (without seeing the command in command mode) using `vim.cmd` or `<cmd>...<cr>` or anything else.

The closest I got was:

```lua
vim.keymap.set("x", "<leader>ci", [['<,'>CodeSnap]])
```

This almost worked but the first time I enter visual mode I get a "Mark not set" error, which is something to do with `<` and `>`. I'n not sure why it doesn't register the marks the first time (vim issue, plugin issue, something else???) but if you exit visual mode and then try again it seems to work. But I didn't want it to be temperamental so I've settled for the mapping I put at the top.

**Comment by peter-bread** [comment]
@jacobrreed 
This is the best I've managed so far:

```lua
keys = {
    { "<leader>ci", ":CodeSnap<cr>", desc = "CodeSnap", mode = "x" },
},
```

It works fine but due to using the `:` you do briefly see that you've entered command mode. If that doesn't bother you then this will suffice.

I'm yet to find a way to do it silently (without seeing the command in command mode) using `vim.cmd` or `<cmd>...<cr>` or anything else.

The closest I got was:

```lua
vim.keymap.set("x", "<leader>ci", [['<,'>CodeSnap]])
```

This almost worked but the first time I enter visual mode I get a "Mark not set" error, which is something to do with `<` and `>`. I'n not sure why it doesn't register the marks the first time (vim issue, plugin issue, something else???) but if you exit visual mode and then try again it seems to work. But I didn't want it to be temperamental so I've settled for the mapping I put at the top.

**Comment by jacobrreed** [comment]
> m

ah Ok this works great, `x` mode was the answer, also to stop the above from bothering you just add `silent=true`

This is my setup now, works good
![image](https://github.com/mistricky/codesnap.nvim/assets/25580051/6ad5f9b3-2bb2-4e8a-a7f2-11f1e0454dd8)


Unfortunately this doesnt work for CodeSnapSave
```
 {
      "<leader>sS",
      ":CodeSnapSave<cr>",
      desc = "CodeSnap save to ~/codesnap",
      mode = "x",
      silent = true,
    },

```

**Comment by jacobrreed** [comment]
@mistricky  Might want to add some documentation on keybind setup, the above seems to work thanks

**Comment by peter-bread** [comment]
> also to stop the above from bothering you just add `silent=true`

Thank you!

**Comment by mistricky** [comment]
Hi @jacobrreed, thx for this issue, sorry reply late.

> Might want to add some documentation on keybind setup

Add keybind setup to document would be great! I'll document it later

**Comment by mistricky** [comment]
The Keymappings chapter was updated on README.

**Comment by bhingston-va** [comment]
If you don't use lazy.nvim as package manager how do you set configuration for code snap? Tried in vim to `:help CodeSnap` or searching for how to set up configuration. I also don't use lua but just vim files.

https://github.com/mistricky/codesnap.nvim?tab=readme-ov-file#keymappings
